TYPE_ACCELEROMETER = 1
TYPE_MAGNETIC_FIELD = 2
TYPE_GYROSCOPE = 4
TYPE_TEMPERATURE = 13
TYPE_IMU_TEMPERATURE = 14
TYPE_SOC_TEMPERATURE = 15

FACING_EARTH = 20
FACING_SKY = 21

GRAVITY = 9.80665

IMU_CALIBRATION_FILENAME = "imu_calibration.json"
